//
//  Item.swift
//  SmartTutor
//
//  This file was generated by the Xcode SwiftData template and is no longer needed.
//  The app uses Core Data for persistence (see Core/Persistence/ — added in Sprint 5).
//
//  Safe to delete via Xcode's project navigator (right-click → Delete).
//
